# Generated by Django 5.0.2 on 2024-03-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_posted',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=2, upload_to='blog_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
