# Generated by Django 5.0.2 on 2024-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
